spring.application.name=calculator

calculator.base-rate=${CALCULATOR_BASE_RATE:20.0}
calculator.insurance-rate-delta=${CALCULATOR_INSURANCE_RATE_DELTA:-3.0}
calculator.salary-client-delta=${CALCULATOR_SALARY_CLIENT_DELTA:-1.0}

server.port=${SERVER_PORT:8081}